---
title: "Fisher_river"
author: "Austin Castelo"
date: "September 7, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Initialize time series
```{r}
library(readxl)
fisher_river <- read_excel("C:/Users/caste/Desktop/fisher_river.xlsx", col_types = c("date", "numeric"))
colnames(fisher_river)[colnames(fisher_river)=='Mean daily temperature, Fisher River near Dallas, Jan 01, 1988 to Dec 31, 1991'] <- "Temp"
fisher_river$Temp <- fisher_river$Temp + 100
temp <- ts(fisher_river$Temp[1:1096])
date <- fisher_river$Date[1:1096]
ts.plot(temp)
```



```{r}
op <- par(mfrow = c(1,2))
acf(temp, lag.max = 50, main = "ACF")
pacf(temp, lag.max = 50, main = "PACF")
par(op)
```


```{r}
temp_diff <- diff(temp)
var(temp_diff)
ts.plot(temp_diff)
op <- par(mfrow = c(1,2))
acf(temp_diff, lag.max = 50, main = "ACF")
pacf(temp_diff, lag.max = 50, main = "PACF", ylim = c(-0.5,0.5))
par(op)
```

```{r}
temp_diff_diff12 <- diff(temp_diff, lag=12)
var(temp_diff_diff12)
ts.plot(temp_diff_diff12)
op <- par(mfrow = c(1,2))
acf(temp_diff_diff12, lag.max = 50, main = "ACF")
pacf(temp_diff_diff12, lag.max = 50, main = "PACF", ylim = c(-0.5,0.5))
par(op)
```

```{r}
data_fit = arima(temp_diff, order = c(0,0,0), method = "ML")
AIC(data_fit) 
for (i in 0:3){for (j in 0:3){ print(i); print(j); print(AIC(arima(temp_diff, order = c(i,0,j), method = "ML")))}}
```

```{r}
arima0 <- arima(temp, order = c(2, 1, 1), method = "ML")
arima0
arima1 <- arima(temp, order = c(1, 1, 2), method = "ML")
arima1
arima2 <- arima(temp, order = c(3, 1, 2), method = "ML")
arima2
```
```{r}
plot.roots <- function(ar.roots=NULL, ma.roots=NULL, size=2, angles=FALSE, special=NULL, sqecial=NULL,my.pch=1,first.col="blue",second.col="red",main=NULL)
{xylims <- c(-size,size)
      omegas <- seq(0,2*pi,pi/500)
      temp <- exp(complex(real=rep(0,length(omegas)),imag=omegas))
      plot(Re(temp),Im(temp),typ="l",xlab="x",ylab="y",xlim=xylims,ylim=xylims,main=main)
      abline(v=0,lty="dotted")
      abline(h=0,lty="dotted")
      if(!is.null(ar.roots))
        {
          points(Re(1/ar.roots),Im(1/ar.roots),col=first.col,pch=my.pch)
          points(Re(ar.roots),Im(ar.roots),col=second.col,pch=my.pch)
        }
      if(!is.null(ma.roots))
        {
          points(Re(1/ma.roots),Im(1/ma.roots),pch="*",cex=1.5,col=first.col)
          points(Re(ma.roots),Im(ma.roots),pch="*",cex=1.5,col=second.col)
        }
      if(angles)
        {
          if(!is.null(ar.roots))
            {
              abline(a=0,b=Im(ar.roots[1])/Re(ar.roots[1]),lty="dotted")
              abline(a=0,b=Im(ar.roots[2])/Re(ar.roots[2]),lty="dotted")
            }
          if(!is.null(ma.roots))
            {
              sapply(1:length(ma.roots), function(j) abline(a=0,b=Im(ma.roots[j])/Re(ma.roots[j]),lty="dotted"))
            }
        }
      if(!is.null(special))
        {
          lines(Re(special),Im(special),lwd=2)
        }
      if(!is.null(sqecial))
        {
          lines(Re(sqecial),Im(sqecial),lwd=2)
        }
        }
```

```{r}
plot.roots(NULL,polyroot(c(1,0.8569,  -0.2291)), main="roots of AR for model0")
plot.roots(NULL,polyroot(c(1, -0.8569)), main="roots of MA for model0")
plot.roots(NULL,polyroot(c(1,0.5750)), main="roots of nonseasonal AR of model1")
plot.roots(NULL,polyroot(c(1,-0.5703,  -0.2682)), main="roots of seasonal MA of model1")
plot.roots(NULL,polyroot(c(1,0.0678,  0.4370,  -0.1497)), main="roots of nonseasonal AR of model2")
plot.roots(NULL,polyroot(c(1, -0.0588,  -0.6942)), main="roots of seasonal MA of model2")
```
Both model 1 and 2 have roots in the unit cirlce, since model 1 is simplier and has a slightly lower AIC we take model 1.

```{r}
final <- arima1
Box.test(residuals(final), type = "Ljung-Box")
Box.test(residuals(final), type = "Box-Pierce")
shapiro.test(residuals(final))
qqnorm(residuals(final))
qqline(residuals(final))
hist(residuals(final))
```
```{r}
library(MLmetrics)
pred <- predict(final, n.ahead = 365)
y_true <- fisher_river$Temp[1097:1461]
y_pred <- pred$pred
length(y_true)
length(y_pred)
mean(abs((y_true - y_pred)/y_true))
```

